baseURL = "https://woomy4680-exe.github.io/Calculate-install"
languageCode = "fr-fr"
title = "Installer calculate GNU/Linux"
theme = "PaperMod"
[params.homeInfoParams]
Title = "Plop 👋"
Content = "Guide d'installation de Calculate GNU/Linux"
[params]
socialIcons = [ { name = "github", url = "https://github.com/Woomy4680-exe/Calculate-install" } ]
