baseURL = "https://calculate-install.woomy.be"
languageCode = "fr-fr"
title = "Installer calculate GNU/Linux"
theme = "PaperMod"
[params.homeInfoParams]
Title = "Plop 👋"
Content = "Guide d'installation de Calculate GNU/Linux"
[params]
socialIcons = [ { name = "github", url = "https://github.com/Woomymy/calculate-install" } ]
